repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-builtin-literals
    - id: check-docstring-first
    - id: check-executables-have-shebangs
      exclude: (.cfg$|.ini$|.toml$|.md$|.txt$|.py$)
      exclude_types: [ yaml, markdown ]
    - id: name-tests-test
      args:
        - --pytest-test-first
      files: tests/utils, tests/fixtures
      exclude: files
- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: python
      language_version: python3.10
      types: [ python ]
    - id: flake8
      name: flake8
      entry: flake8 --config setup.cfg
      language: python
      language_version: python3.10
      types: [ python ]
      args: ['--ignore=F405']
    - id: isort
      name: isort
      entry: isort
      language: python
      types: [ python ]
      args:
        - --profile
        -  black
        - --filter-files
    - id: mypy
      name: mypy
      entry: mypy
      language: python
      types: [ python ]
    - id: pytest
      name: pytest
      entry: pytest --no-header -v
      language: python
      types: [ python ]
      pass_filenames: false
