from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(100) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `event` (
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `start_date` DATETIME(6) NOT NULL,
    `end_date` DATETIME(6) NOT NULL,
    `title` VARCHAR(50) NOT NULL,
    `is_display` BOOL NOT NULL,
    `page_url` VARCHAR(2048),
    `end_page_url` VARCHAR(2048),
    `banner_image_url` VARCHAR(2048),
    `list_image_url` VARCHAR(2048),
    `is_delete` BOOL   DEFAULT 1
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `user` (
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(10) NOT NULL,
    `password` VARCHAR(60) NOT NULL,
    `account_level` VARCHAR(6) NOT NULL  COMMENT 'BRONZE: BRONZE\nSILVER: SILVER\nGOLD: GOLD',
    `status` BOOL NOT NULL  DEFAULT 1,
    `authenticated` VARCHAR(7) NOT NULL  COMMENT 'NOT_YET: NOT_YET\nEMAIL: EMAIL\nSNS: SNS\nPHONE: PHONE' DEFAULT 'NOT_YET'
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `userorder` (
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `status` VARCHAR(20) NOT NULL  COMMENT 'REQUEST: REQUEST\nPROCESSING: PROCESSING\nCOMPLETED: COMPLETED\nCANCEL_AUTO: CANCEL_AUTO\nCANCEL_USER: CANCEL_USER\nCANCEL_ADMIN: CANCEL_ADMIN',
    `order_date` DATETIME(6) NOT NULL,
    `complete_date` DATETIME(6),
    `amount` DECIMAL(10,3) NOT NULL  DEFAULT 0,
    `user_id` BIGINT NOT NULL,
    KEY `idx_userorder_order_d_0f29ec` (`order_date`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `adminuser` (
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(10) NOT NULL,
    `password` VARCHAR(60) NOT NULL,
    `role` VARCHAR(10) NOT NULL
) CHARACTER SET utf8mb4;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """
